name: Continuous Integration

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
      - '.editorconfig'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
      - '.editorconfig'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.0'
          - '3.0.5'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Standard
      run: bundle exec rake standard
    - name: Run Tests
      run: bundle exec rake test
